name: how_you_doin
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.1
  google_fonts: ^2.1.0
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Authenia
      fonts:
        - asset: fonts/Authenia.ttf
    - family: Brickson
      fonts:
        - asset: fonts/BricksonFree.ttf
    - family: LemonMilk
      fonts:
        - asset: fonts/LemonMilkBold.ttf
        - asset: fonts/LemonMilkLightItalic.ttf
        - asset: fonts/LemonMilkMedium.ttf
        - asset: fonts/LemonMilkMediumItalic.ttf
        - asset: fonts/LemonMilkRegular.ttf
        - asset: fonts/LemonMilkRegularItalic.ttf
    - family: LibraryRecordsRegular
      fonts:
        - asset: fonts/LibraryRecordsRegular.ttf
    - family: LuckySkirtRegular
      fonts:
        - asset: fonts/LuckySkirtRegular.ttf
    - family: MoongladeDemoBold
      fonts:
        - asset: fonts/MoongladeDemoBold.ttf
    - family: PotteryWheelRegular
      fonts:
        - asset: fonts/PotteryWheelRegular.ttf
    - family: Southampton
      fonts:
        - asset: fonts/Southampton.ttf
    - family: StoryElementRegular
      fonts:
        - asset: fonts/StoryElementRegular.ttf
    - family: Sundaycoffee
      fonts:
        - asset: fonts/Sundaycoffee.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
