name: howyoudoin
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.4
  colorful_safe_area: ^0.3.0
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  firebase_auth: ^3.3.3
  firebase_core: ^1.10.5
  firebase_storage: ^10.2.3
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.4.1
  flutter_svg: ^1.0.0
  get: ^4.6.1
  google_fonts: ^2.2.0
  hexcolor: ^2.0.5
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  intro_slider: ^3.0.2
  loading_animation_widget: ^1.1.0+1
  provider: ^6.0.1
  rive: ^0.8.1
  uuid: ^3.0.5

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Authenia
      fonts:
        - asset: fonts/Authenia.ttf
    - family: Brickson
      fonts:
        - asset: fonts/BricksonFree.ttf
    - family: LemonMilk
      fonts:
        - asset: fonts/LemonMilkBold.ttf
        - asset: fonts/LemonMilkLightItalic.ttf
        - asset: fonts/LemonMilkMedium.ttf
        - asset: fonts/LemonMilkMediumItalic.ttf
        - asset: fonts/LemonMilkRegular.ttf
        - asset: fonts/LemonMilkRegularItalic.ttf
    - family: LibraryRecordsRegular
      fonts:
        - asset: fonts/LibraryRecordsRegular.ttf
    - family: LuckySkirtRegular
      fonts:
        - asset: fonts/LuckySkirtRegular.ttf
    - family: MoongladeDemoBold
      fonts:
        - asset: fonts/MoongladeDemoBold.ttf
    - family: PotteryWheelRegular
      fonts:
        - asset: fonts/PotteryWheelRegular.ttf
    - family: Southampton
      fonts:
        - asset: fonts/Southampton.ttf
    - family: StoryElementRegular
      fonts:
        - asset: fonts/StoryElementRegular.ttf
    - family: Sundaycoffee
      fonts:
        - asset: fonts/Sundaycoffee.ttf
